apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init-ctr
  labels:
    env: uat
  namespace: uat
spec:
  initContainers:
    - name: init-ctr
      image: busybox:1.28.4
      command: ["sh","-c","until nslookup k8sbook; do echo waiting for svc k8sbook; sleep 1; done; echo svc found !"]
  containers:
    - name: web-str
      image: nigelpoulton/web-app:1.0
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8sbook
  namespace: uat
  labels:
    env: uat
spec:
  type: ClusterIP
  selector:
    env: uat
  ports:
    - targetPort: 8080 #the port on the target container
      port: 80
        #nodePort: 30001

