apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  labels:
    app: sidecar
    env: uat
  namespace: uat
spec:
  containers:
    - name: web-ctr
      image: nginx
      volumeMounts:
        - name: html
          mountPath:  /usr/share/nginx
    - name: ctr-sync
      image:  k8s.gcr.io/git-sync:v3.1.6
      volumeMounts:
        - name: html
          mountPath:  /tmp/git
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/TusharThapliyal/ps-sidecar
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: "html"
  volumes:
    - name: html
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: svc-for-sidecar-pod
  namespace: uat
  labels:
    app: sidecar
    env: uat
spec:
  type: NodePort
  selector:
    env: uat
  ports:
    - targetPort: 80 #the port on the target container
      port: 80
      nodePort: 30001

