apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-pod-in-uat-namespace
rules:
- apiGroups: [""]                
  resources: ["pods"]                
  verbs: ["get","list","watch","create","delete"]                   

