apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-pod-in-uat-namespace-binding
  namespace: uat
subjects:
- kind: User
  name: tushar                # The username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: get-pod-in-uat-namespace      # Name of the ClusterRole
  apiGroup: rbac.authorization.k8s.io

