apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-access-binding
  namespace: kube-system
subjects:
- kind: User
  name: tushar                # The username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: full-access-role      # Name of the ClusterRole
  apiGroup: rbac.authorization.k8s.io

